spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_mgt?useSSL=false&serverTimezone=UTC
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 根据实体类自动创建和更新数据库表结构，开发阶段使用，生产环境建议设置为 none
    show-sql: true  # 打印 SQL 语句，方便调试
server:
  port: 8080  # 设置 Spring Boot 应用的端口号